//-----------------------------------------------------------------------------
// File : gmsBitmapClass.h
// Date : 04-Nov-99 : initial definition
//        10-Nov-99 : code-review and clean-up
//
// Description:
//    This class defines a "device-independent bitmap" (DIB) object.  The
//    bitmap is created from the window whose handle is given in the
//    constructor.  The DIB can be saved to a file.  Such an object can be
//    used to implement "screen capture".
//
//    The DIB object (generated by this component) is fixed to a resolution
//    of 256 colors.  Such resolution (nowadays) is likely to be lower than
//    the resolution of most video hardware systems.  This was done because
//    many video boards no longer require a color lookup-table (i.e. a color
//    palette).  For example, this component was actually built/tested on a
//    PC system with a video card that implemented a 16-bit pixel.  The
//    RED and BLUE values were 5 bits and the GREEN value was 6 bits.  This
//    allowed for a range of 65535 colors without the need for a color table.
//    Furthermore, some systems now have 24 bit pixels (8-bits for each RGB).
//
//    But a DIB must include a color table ... at least if it is to be
//    read by the VC++ bitmap editor.  So, to keep things from getting out
//    of hand, the following "restrictions" (simplifications) were
//    implemented:
//
//           1) The color table has 256 entries (only).
//           2) Each pixel of the image is one byte (8 bits).
//           3) Each pixel value is an index into the color table.
//           4) No compression is used.
//           5) The simpler struct "BITMAPINFOHEADER" is used
//              (in lieu of "BITMAPV4HEADER" or "BITMAPV5HEADER").
//
// Acronyms:
//    DDB - Device Dependent Bitmap
//    DIB - Device Independent Bitmap
//    BM  - Bitmap
//    DC  - Device Context (i.e. Windows abstraction to video hardware)
//    GMS - Geographic Mapping System
//
// Copyright (c) 1999-2026, Timothy MacAndrew, all rights reserved
//-----------------------------------------------------------------------------

#ifndef GMS_BITMAP

   #define GMS_BITMAP

   #include <windows.h>

   class gmsBitmapClass
      {
       public:

          //-----------------------------------------------
          // gmsBitmapClass
          //
          // Description:
          //    Constructor.  Creates a device-independent
          //    bitmap from the specified window handle.
          //-----------------------------------------------
          gmsBitmapClass (HWND windowHandle);


          //-----------------------------------------------
          // gmsBitmapClass
          //
          // Description:
          //    Constructor.  Opens a device-independent
          //    bitmap from the named file.
          //-----------------------------------------------
          gmsBitmapClass (const char *nameOfFile);


          //-----------------------------------------------
          // ~gmsBitmapClass
          //
          // Description:
          //    Destructor.  Deletes the device-independent
          //    bitmap.
          //-----------------------------------------------
          ~gmsBitmapClass ();


          //-----------------------------------------------
          // gmsSaveBitmap
          //
          // Description:
          //    Method to save the device-independent
          //    bitmap to the specified file.
          //-----------------------------------------------
          void gmsSaveBitmap (const char *nameOfFile);


          //-----------------------------------------------
          // gmsPrintContentsOfBitmap
          //
          // Description:
          //    Method that writes the contents of the
          //    bitmap object to a file.
          //-----------------------------------------------
          void gmsPrintContentsOfBitmap (const char *nameOfFile);

       private:

          typedef struct
             {
              BITMAPFILEHEADER bitmapFileHdr;
              BITMAPINFOHEADER bitmapInfoHdr;
              RGBQUAD          *ptrToColorTbl;
              BYTE             *ptrToImage;
             } gmsDeviceIndependentBitmapType;

          gmsDeviceIndependentBitmapType theDIB;
      };

#endif
