//-------------------------------------------------------------------------
// File : dcw_browse_main_window.h
// Date : 26-May-26 : initial definition
//
// Description:
//    A Qt program that exercises the "browse" library of DCW database.
//    This file was orignally generated by the 'Qt Creator' tool as a
//    starting point.  Will be built up over time as more DCW/LibRef
//    functionality is added.
//-------------------------------------------------------------------------
#ifndef DCW_BROWSE_MAIN_WINDOW_H
#define DCW_BROWSE_MAIN_WINDOW_H

#include <QMainWindow>

#include "tables_dialog.h"
#include "dcw_browse.h"


QT_BEGIN_NAMESPACE
namespace Ui { class dcw_browse_Main_Window; }
QT_END_NAMESPACE

class dcw_browse_Main_Window : public QMainWindow
{
    Q_OBJECT

public:
    dcw_browse_Main_Window
          (const std::string earth_model,
           QWidget *parent = nullptr);

    ~dcw_browse_Main_Window();

public slots:

   void exit();

   void process_map_ctrl_button_click();

   void process_browse_map_button_click();

   void process_table_button_click();

   void process_NOAMER_button_click();

   void process_EURNASIA_button_click();

   void process_SOAMAFR_button_click();

   void process_SASAUS_button_click();

   void process_TileRef_lat_long_button_click();

private:
    Ui::dcw_browse_Main_Window *ui = nullptr;

    DCW_Browse                 *browse_map = nullptr;

    Tables_Dialog_Window       *table_info_dialog = nullptr;

    gmsLatLongGridClass        *tile_ref_grid = nullptr;

    gmsTileClass               *theTileMap = nullptr;

    gmsTileClass               *tile_ref_maps[NUM_TILE_REF_MAPS] = { nullptr };
                        
};
#endif // DCW_BROWSE_MAIN_WINDOW_H

/* EOF */

