//-------------------------------------------------------------------------
// File : dcw_browse_main_window.cpp
// Date : 26-May-26 : initial definition
//
// Description:
//    A Qt program that exercises the "browse" library of DCW database.
//    This file was orignally generated by the 'Qt Creator' tool as a
//    starting point.  Will be built up over time as more DCW/LibRef
//    functionality is added.
//-------------------------------------------------------------------------
#include <iostream>

#include <QPainter>
#include <QPaintEvent>

#include <QSplitter>
#include <QWidget>
#include <QHBoxLayout>

#include "dcw_browse.h"
#include "dcw_browse_main_window.h"
#include "ui_dcw_browse_main_window.h"


//========================================================
// METHOD: dcw_browse_Main_Window
//
// DESCRIPTION:
//    Constructor as entry point to create the GUI/Window
//    of the application.
//========================================================
dcw_browse_Main_Window::dcw_browse_Main_Window
                           (const std::string earth_model,
                            QWidget *parent)

    : QMainWindow(parent),
      ui(new Ui::dcw_browse_Main_Window)

{
    ui->setupUi(this);

    QWidget *central = ui->centralwidget;

    setCentralWidget(central);

    map_window = new DCW_Browse(earth_model, this);

    QSplitter *splitter = new QSplitter(Qt::Horizontal, this);

    splitter->addWidget(map_window);

    splitter->setSizes({400, 100});

    QHBoxLayout *layout = new QHBoxLayout(central);

    layout->addWidget(splitter);

    connect(ui->actionExit,
            &QAction::triggered,
            this,
            &dcw_browse_Main_Window::exit);

    connect(ui->actionZoom_in,
            &QAction::triggered,
            this,
            &dcw_browse_Main_Window::zoom_in);

    connect(ui->actionZoom_out,
            &QAction::triggered,
            this,
            &dcw_browse_Main_Window::zoom_out);

    connect(ui->actionMove_North,
            &QAction::triggered,
            this,
            &dcw_browse_Main_Window::move_north);

    connect(ui->actionMove_South,
            &QAction::triggered,
            this,
            &dcw_browse_Main_Window::move_south);

    connect(ui->actionMove_East,
            &QAction::triggered,
            this,
            &dcw_browse_Main_Window::move_east);

    connect(ui->actionMove_West,
            &QAction::triggered,
            this,
            &dcw_browse_Main_Window::move_west);

    connect(ui->actionLibRef,
            &QAction::triggered,
            this,
            &dcw_browse_Main_Window::show_lib_ref);

    connect(ui->actionPopulation,
            &QAction::triggered,
            this,
            &dcw_browse_Main_Window::show_population);

    connect(ui->actionDrainage,
            &QAction::triggered,
            this,
            &dcw_browse_Main_Window::show_drainage);

    connect(ui->actionPolit_Ocean,
            &QAction::triggered,
            this,
            &dcw_browse_Main_Window::show_polit_ocean);

    connect(ui->actionDatabase_Header,
            &QAction::triggered,
            this,
            &dcw_browse_Main_Window::show_database_header);

    connect(ui->actionLibrary_Attributes,
            &QAction::triggered,
            this,
            &dcw_browse_Main_Window::show_library_attributes);

    connect(ui->actionCoverage_Attributes,
            &QAction::triggered,
            this,
            &dcw_browse_Main_Window::show_coverage_attributes);

    connect(ui->actionData_Quality,
            &QAction::triggered,
            this,
            &dcw_browse_Main_Window::show_data_quality);

    connect(ui->actionGeographic_Reference,
            &QAction::triggered,
            this,
            &dcw_browse_Main_Window::show_geographic_reference);

    connect(ui->actionLibrary_Header,
            &QAction::triggered,
            this,
            &dcw_browse_Main_Window::show_library_header);

    connect(ui->actionSOAMAFR,
            &QAction::triggered,
            this,
            &dcw_browse_Main_Window::show_SOAMAFR);
}

dcw_browse_Main_Window::~dcw_browse_Main_Window()
{
    if (table_info_dialog)
    {
        delete table_info_dialog;
        table_info_dialog = nullptr;
    }

    if (map_window)
    {
        delete map_window;
        map_window = nullptr;
    }

    delete ui;
}

void dcw_browse_Main_Window::exit()
{
   std::exit(0);
}

void dcw_browse_Main_Window::zoom_in()
{
    std::cout << "Zoom in\n";

    map_window->zoom("in");
}

void dcw_browse_Main_Window::zoom_out()
{
    std::cout << "Zoom out\n";

    map_window->zoom("out");
}

void dcw_browse_Main_Window::move_north()
{
    std::cout << "Move North\n";

    map_window->move("north");
}

void dcw_browse_Main_Window::move_south()
{
    std::cout << "Move South\n";

    map_window->move("south");
}

void dcw_browse_Main_Window::move_east()
{
    std::cout << "Move East\n";

    map_window->move("east");
}

void dcw_browse_Main_Window::move_west()
{
    std::cout << "Move West\n";

    map_window->move("west");
}

void dcw_browse_Main_Window::show_lib_ref()
{
    std::cout << "Show LibRef\n";

    QAction *lr_button = ui->actionLibRef;

    bool state = lr_button->isChecked();

    map_window->setMapState(gmsBrowse_LibRef, state);
}

void dcw_browse_Main_Window::show_population()
{
    std::cout << "Show Population\n";

    QAction *pp_button = ui->actionPopulation;

    bool state = pp_button->isChecked();

    map_window->setMapState(gmsBrowse_PP, state);
}

void dcw_browse_Main_Window::show_drainage()
{
    std::cout << "Show Drainage\n";

    QAction *dn_button = ui->actionDrainage;

    bool state = dn_button->isChecked();

    map_window->setMapState(gmsBrowse_DN, state);
}

void dcw_browse_Main_Window::show_polit_ocean()
{
    std::cout << "Show Polit-Ocean\n";

    QAction *po_button = ui->actionPolit_Ocean;

    bool state = po_button->isChecked();

    map_window->setMapState(gmsBrowse_PO, state);
}

void dcw_browse_Main_Window::show_database_header()
{
    std::cout << "show_database_header\n";

    if ( not table_info_dialog )
    {   
        table_info_dialog = new Tables_Dialog_Window(this);
    }

    table_info_dialog->show();
}

void dcw_browse_Main_Window::show_library_attributes()
{
    std::cout << "show_library_attributes\n";

    if ( not table_info_dialog )
    {
        table_info_dialog = new Tables_Dialog_Window(this);
    }

    table_info_dialog->show();
}

void dcw_browse_Main_Window::show_coverage_attributes()
{
    std::cout << "show_coverage_attributes\n";

    if ( not table_info_dialog )
    {
        table_info_dialog = new Tables_Dialog_Window(this);
    }

    table_info_dialog->show();
}

void dcw_browse_Main_Window::show_data_quality()
{
    std::cout << "show_data_quality\n";

    if ( not table_info_dialog )
    {
        table_info_dialog = new Tables_Dialog_Window(this);
    }

    table_info_dialog->show();
}

void dcw_browse_Main_Window::show_geographic_reference()
{
    std::cout << "show_geographic_reference\n";

    if ( not table_info_dialog )
    {
        table_info_dialog = new Tables_Dialog_Window(this);
    }

    table_info_dialog->show();
}

void dcw_browse_Main_Window::show_library_header()
{
    std::cout << "show_library_header\n";

    if ( not table_info_dialog )
    {
        table_info_dialog = new Tables_Dialog_Window(this);
    }

    table_info_dialog->show();
}

void dcw_browse_Main_Window::show_SOAMAFR()
{
    std::cout << "show_SOAMAFR\n";
}

/* EOF */

