//-------------------------------------------------------------------------
// File : dcw_browse_main_window.h
// Date : 26-May-26 : initial definition
//
// Description:
//    A Qt program that exercises the "browse" library of DCW database.
//    This file was orignally generated by the 'Qt Creator' tool as a
//    starting point.  Will be built up over time as more DCW/LibRef
//    functionality is added.
//-------------------------------------------------------------------------
#ifndef DCW_BROWSE_MAIN_WINDOW_H
#define DCW_BROWSE_MAIN_WINDOW_H

#include <QMainWindow>

#include "tables_dialog.h"
#include "dcw_browse.h"
#include "dcw_library_mgr.h"


QT_BEGIN_NAMESPACE
namespace Ui { class dcw_browse_Main_Window; }
QT_END_NAMESPACE

class dcw_browse_Main_Window : public QMainWindow
{
    Q_OBJECT

public:
    dcw_browse_Main_Window
          (const std::string earth_model,
           QWidget *parent = nullptr);

    ~dcw_browse_Main_Window();

public slots:

   void exit();

   // Ctrl
   void zoom_in();

   void zoom_out();

   void move_north();

   void move_south();

   void move_east();

   void move_west();

   // Map Themes
   void show_lib_ref();

   void show_population();

   void show_drainage();

   void show_polit_ocean();

   // Tables
   void show_database_header();

   void show_library_attributes();

   void show_coverage_attributes();

   void show_data_quality();

   void show_geographic_reference();

   void show_library_header();

   // Tile Ref
   void show_SOAMAFR();

private:
    Ui::dcw_browse_Main_Window *ui = nullptr;

    DCW_Browse *browse_map         = nullptr;

    DCW_Library_Mgr *lib_map       = nullptr;

    Tables_Dialog_Window *table_info_dialog = nullptr;
};
#endif // DCW_BROWSE_MAIN_WINDOW_H

/* EOF */

