//-------------------------------------------------------------------------
// File : dcw_browse_main_window.cpp
// Date : 26-May-26 : initial definition
//
// Description:
//    A Qt program that exercises the "browse" library of DCW database.
//    This file was orignally generated by the 'Qt Creator' tool as a
//    starting point.  Will be built up over time as more DCW/LibRef
//    functionality is added.
//-------------------------------------------------------------------------
#include <iostream>

#include <QPainter>
#include <QPaintEvent>

#include <QSplitter>
#include <QWidget>
#include <QHBoxLayout>

#include "dcw_browse.h"
#include "dcw_browse_main_window.h"
#include "ui_dcw_browse_main_window.h"


//========================================================
// METHOD: dcw_browse_Main_Window
//
// DESCRIPTION:
//    Constructor as entry point to create the GUI/Window
//    of the application.
//========================================================
dcw_browse_Main_Window::dcw_browse_Main_Window(QWidget *parent)

    : QMainWindow(parent),
      ui(new Ui::dcw_browse_Main_Window)

{
    ui->setupUi(this);

    QWidget *central = ui->centralwidget;

    setCentralWidget(central);

    map_window = new DCW_Browse(this);

    QSplitter *splitter = new QSplitter(Qt::Horizontal, this);

    splitter->addWidget(map_window);

    splitter->setSizes({400, 100});

    QHBoxLayout *layout = new QHBoxLayout(central);

    layout->addWidget(splitter);

    connect(ui->actionExit,
            &QAction::triggered,
            this,
            &dcw_browse_Main_Window::exit_action_slot);
}

dcw_browse_Main_Window::~dcw_browse_Main_Window()
{
    if (map_window)
    {
        delete map_window;
        map_window = nullptr;
    }

    delete ui;
}

void dcw_browse_Main_Window::exit_action_slot()
{
   std::exit(0);
}

/* EOF */

