//-------------------------------------------------------------------------
// File : dcw_browse_main_window.cpp
// Date : 26-May-26 : initial definition
//
// Description:
//    A Qt program that exercises the "browse" library of DCW database.
//    This file was orignally generated by the 'Qt Creator' tool as a
//    starting point.  Will be built up over time as more DCW/LibRef
//    functionality is added.
//-------------------------------------------------------------------------
#include <iostream>

#include <QPainter>
#include <QPaintEvent>

#include <QSplitter>
#include <QWidget>
#include <QHBoxLayout>

#include "dcw_browse.h"
#include "dcw_browse_main_window.h"
#include "ui_dcw_browse_main_window.h"


//========================================================
// METHOD: dcw_browse_Main_Window
//
// DESCRIPTION:
//    Constructor as entry point to create the GUI/Window
//    of the application.
//========================================================
dcw_browse_Main_Window::dcw_browse_Main_Window
                           (const std::string earth_model,
                            QWidget *parent)

    : QMainWindow(parent),
      ui(new Ui::dcw_browse_Main_Window)

{
    ui->setupUi(this);

    QWidget *central = ui->centralwidget;

    setCentralWidget(central);

    browse_map = new DCW_Browse(earth_model, this);

    QSplitter *splitter = new QSplitter(Qt::Horizontal, this);

    splitter->addWidget(browse_map);

    splitter->setSizes({400, 100});

    QHBoxLayout *layout = new QHBoxLayout(central);

    layout->addWidget(splitter);

    connect(ui->actionExit,
            &QAction::triggered,
            this,
            &dcw_browse_Main_Window::exit);

    connect(ui->actionZoom_in,
            &QAction::triggered,
            this,
            &dcw_browse_Main_Window::zoom_in);

    connect(ui->actionZoom_out,
            &QAction::triggered,
            this,
            &dcw_browse_Main_Window::zoom_out);

    connect(ui->actionMove_North,
            &QAction::triggered,
            this,
            &dcw_browse_Main_Window::move_north);

    connect(ui->actionMove_South,
            &QAction::triggered,
            this,
            &dcw_browse_Main_Window::move_south);

    connect(ui->actionMove_East,
            &QAction::triggered,
            this,
            &dcw_browse_Main_Window::move_east);

    connect(ui->actionMove_West,
            &QAction::triggered,
            this,
            &dcw_browse_Main_Window::move_west);

    connect(ui->action_Lat_Long_Grid,
            &QAction::triggered,
            this,
            &dcw_browse_Main_Window::show_lat_long_grid);

    connect(ui->actionLibRef,
            &QAction::triggered,
            this,
            &dcw_browse_Main_Window::show_lib_ref);

    connect(ui->actionPopulation,
            &QAction::triggered,
            this,
            &dcw_browse_Main_Window::show_population);

    connect(ui->actionDrainage,
            &QAction::triggered,
            this,
            &dcw_browse_Main_Window::show_drainage);

    connect(ui->actionPolit_Ocean,
            &QAction::triggered,
            this,
            &dcw_browse_Main_Window::show_polit_ocean);

    connect(ui->actionDatabase_Header,
            &QAction::triggered,
            this,
            &dcw_browse_Main_Window::show_database_header);

    connect(ui->actionLibrary_Attributes,
            &QAction::triggered,
            this,
            &dcw_browse_Main_Window::show_library_attributes);

    connect(ui->actionCoverage_Attributes,
            &QAction::triggered,
            this,
            &dcw_browse_Main_Window::show_coverage_attributes);

    connect(ui->actionData_Quality,
            &QAction::triggered,
            this,
            &dcw_browse_Main_Window::show_data_quality);

    connect(ui->actionGeographic_Reference,
            &QAction::triggered,
            this,
            &dcw_browse_Main_Window::show_geographic_reference);

    connect(ui->actionLibrary_Header,
            &QAction::triggered,
            this,
            &dcw_browse_Main_Window::show_library_header);

    // NOAMER Library
    connect(ui->actionNOAMER_Map_Lines,
            &QAction::triggered,
            this,
            &dcw_browse_Main_Window::process_NOAMER);

    connect(ui->actionNOAMER_Political_Oceans,
            &QAction::triggered,
            this,
            &dcw_browse_Main_Window::process_NOAMER);

    connect(ui->actionNOAMER_Drainage_Polygons,
            &QAction::triggered,
            this,
            &dcw_browse_Main_Window::process_NOAMER);

    connect(ui->actionNOAMER_Drainage_Lines,
            &QAction::triggered,
            this,
            &dcw_browse_Main_Window::process_NOAMER);

    connect(ui->actionNOAMER_Text,
            &QAction::triggered,
            this,
            &dcw_browse_Main_Window::process_NOAMER);

    connect(ui->actionNOAMER_Cities,
            &QAction::triggered,
            this,
            &dcw_browse_Main_Window::process_NOAMER);

    connect(ui->actionNOAMER_Hypsographic,
            &QAction::triggered,
            this,
            &dcw_browse_Main_Window::process_NOAMER);

    // EURNASIA Library
    connect(ui->actionEURNASIA_Map_Lines,
            &QAction::triggered,
            this,
            &dcw_browse_Main_Window::process_EURNASIA);

    connect(ui->actionEURNASIA_Political_Oceans,
            &QAction::triggered,
            this,
            &dcw_browse_Main_Window::process_EURNASIA);

    connect(ui->actionEURNASIA_Drainage_Polygons,
            &QAction::triggered,
            this,
            &dcw_browse_Main_Window::process_EURNASIA);

    connect(ui->actionEURNASIA_Drainage_Lines,
            &QAction::triggered,
            this,
            &dcw_browse_Main_Window::process_EURNASIA);

    connect(ui->actionEURNASIA_Text,
            &QAction::triggered,
            this,
            &dcw_browse_Main_Window::process_EURNASIA);

    connect(ui->actionEURNASIA_Cities,
            &QAction::triggered,
            this,
            &dcw_browse_Main_Window::process_EURNASIA);

    connect(ui->actionEURNASIA_Hypsographic,
            &QAction::triggered,
            this,
            &dcw_browse_Main_Window::process_EURNASIA);

    // SOAMAFR Library
    connect(ui->actionSOAMAFR_Map_Lines,
            &QAction::triggered,
            this,
            &dcw_browse_Main_Window::process_SOAMAFR);

    connect(ui->actionSOAMAFR_Political_Oceans,
            &QAction::triggered,
            this,
            &dcw_browse_Main_Window::process_SOAMAFR);

    connect(ui->actionSOAMAFR_Drainage_Polygons,
            &QAction::triggered,
            this,
            &dcw_browse_Main_Window::process_SOAMAFR);

    connect(ui->actionSOAMAFR_Drainage_Lines,
            &QAction::triggered,
            this,
            &dcw_browse_Main_Window::process_SOAMAFR);

    connect(ui->actionSOAMAFR_Text,
            &QAction::triggered,
            this,
            &dcw_browse_Main_Window::process_SOAMAFR);

    connect(ui->actionSOAMAFR_Cities,
            &QAction::triggered,
            this,
            &dcw_browse_Main_Window::process_SOAMAFR);

    connect(ui->actionSOAMAFR_Hypsographic,
            &QAction::triggered,
            this,
            &dcw_browse_Main_Window::process_SOAMAFR);

    // SASAUS Library
    connect(ui->actionSASAUS_Map_Lines,
            &QAction::triggered,
            this,
            &dcw_browse_Main_Window::process_SASAUS);

    connect(ui->actionSASAUS_Political_Oceans,
            &QAction::triggered,
            this,
            &dcw_browse_Main_Window::process_SASAUS);

    connect(ui->actionSASAUS_Drainage_Polygons,
            &QAction::triggered,
            this,
            &dcw_browse_Main_Window::process_SASAUS);

    connect(ui->actionSASAUS_Drainage_Lines,
            &QAction::triggered,
            this,
            &dcw_browse_Main_Window::process_SASAUS);

    connect(ui->actionSASAUS_Text,
            &QAction::triggered,
            this,
            &dcw_browse_Main_Window::process_SASAUS);

    connect(ui->actionSASAUS_Cities,
            &QAction::triggered,
            this,
            &dcw_browse_Main_Window::process_SASAUS);

    connect(ui->actionSASAUS_Hypsographic,
            &QAction::triggered,
            this,
            &dcw_browse_Main_Window::process_SASAUS);

    // LibRef Lat/Long Grid
    connect(ui->actionTileRef_Lat_Long_Grid,
            &QAction::triggered,
            this,
            &dcw_browse_Main_Window::process_LibRef_LatLong);
}

dcw_browse_Main_Window::~dcw_browse_Main_Window()
{
    std::cout << "~~~ dcw_browse_Main_Window - Destructor - begin\n";

    if (table_info_dialog)
    {
        delete table_info_dialog;
        table_info_dialog = nullptr;
    }

    if (browse_map)
    {
        delete browse_map;
        browse_map = nullptr;
    }

    if (NOAMER_map)
    {
        delete NOAMER_map;
        NOAMER_map = nullptr;
    }

    if (EURNASIA_map)
    {
        delete EURNASIA_map;
        EURNASIA_map = nullptr;
    }

    if (SOAMAFR_map)
    {
        delete SOAMAFR_map;
        SOAMAFR_map = nullptr;
    }

    if (SASAUS_map)
    {
        delete SASAUS_map;
        SASAUS_map = nullptr;
    }

    delete ui;
    ui = nullptr;

    std::cout << "~~~ dcw_browse_Main_Window - Destructor - end\n";
}

void dcw_browse_Main_Window::exit()
{
   std::exit(0);
}

void dcw_browse_Main_Window::zoom_in()
{
    std::cout << "Zoom in\n";

    browse_map->zoom("in");
}

void dcw_browse_Main_Window::zoom_out()
{
    std::cout << "Zoom out\n";

    browse_map->zoom("out");
}

void dcw_browse_Main_Window::move_north()
{
    std::cout << "Move North\n";

    browse_map->move("north");
}

void dcw_browse_Main_Window::move_south()
{
    std::cout << "Move South\n";

    browse_map->move("south");
}

void dcw_browse_Main_Window::move_east()
{
    std::cout << "Move East\n";

    browse_map->move("east");
}

void dcw_browse_Main_Window::move_west()
{
    std::cout << "Move West\n";

    browse_map->move("west");
}

void dcw_browse_Main_Window::show_lat_long_grid()
{
    std::cout << "Lat/Long Grid\n";

    QAction *llg_button = ui->action_Lat_Long_Grid;

    bool state = llg_button->isChecked();

    browse_map->setLongLongGridState(state);
}

void dcw_browse_Main_Window::show_lib_ref()
{
    std::cout << "Show LibRef\n";

    QAction *lr_button = ui->actionLibRef;

    bool state = lr_button->isChecked();

    browse_map->setMapState(gmsBrowse_LibRef, state);
}

void dcw_browse_Main_Window::show_population()
{
    std::cout << "Show Population\n";

    QAction *pp_button = ui->actionPopulation;

    bool state = pp_button->isChecked();

    browse_map->setMapState(gmsBrowse_PP, state);
}

void dcw_browse_Main_Window::show_drainage()
{
    std::cout << "Show Drainage\n";

    QAction *dn_button = ui->actionDrainage;

    bool state = dn_button->isChecked();

    browse_map->setMapState(gmsBrowse_DN, state);
}

void dcw_browse_Main_Window::show_polit_ocean()
{
    std::cout << "Show Polit-Ocean\n";

    QAction *po_button = ui->actionPolit_Ocean;

    bool state = po_button->isChecked();

    browse_map->setMapState(gmsBrowse_PO, state);
}

void dcw_browse_Main_Window::show_database_header()
{
    std::cout << "show_database_header\n";

    if ( not table_info_dialog )
    {   
        table_info_dialog = new Tables_Dialog_Window(this);
    }

    table_info_dialog->show();
}

void dcw_browse_Main_Window::show_library_attributes()
{
    std::cout << "show_library_attributes\n";

    if ( not table_info_dialog )
    {
        table_info_dialog = new Tables_Dialog_Window(this);
    }

    table_info_dialog->show();
}

void dcw_browse_Main_Window::show_coverage_attributes()
{
    std::cout << "show_coverage_attributes\n";

    if ( not table_info_dialog )
    {
        table_info_dialog = new Tables_Dialog_Window(this);
    }

    table_info_dialog->show();
}

void dcw_browse_Main_Window::show_data_quality()
{
    std::cout << "show_data_quality\n";

    if ( not table_info_dialog )
    {
        table_info_dialog = new Tables_Dialog_Window(this);
    }

    table_info_dialog->show();
}

void dcw_browse_Main_Window::show_geographic_reference()
{
    std::cout << "show_geographic_reference\n";

    if ( not table_info_dialog )
    {
        table_info_dialog = new Tables_Dialog_Window(this);
    }

    table_info_dialog->show();
}

void dcw_browse_Main_Window::show_library_header()
{
    std::cout << "show_library_header\n";

    if ( not table_info_dialog )
    {
        table_info_dialog = new Tables_Dialog_Window(this);
    }

    table_info_dialog->show();
}

void dcw_browse_Main_Window::process_NOAMER()
{
    std::cout << "process_NOAMER - NOT IMPLEMENTED\n";
}

void dcw_browse_Main_Window::process_EURNASIA()
{
    std::cout << "process_EURNASIA - NOT IMPLEMENTED\n";
}

void dcw_browse_Main_Window::process_SOAMAFR()
{
    std::cout << "process_SOAMAFR - NOT IMPLEMENTED\n";
}

void dcw_browse_Main_Window::process_SASAUS()
{
    std::cout << "process_SASAUS - NOT IMPLEMENTED\n";
}

void dcw_browse_Main_Window::process_LibRef_LatLong()
{
    std::cout << "process_LibRef_LatLong - begin\n";

    if ( ! SOAMAFR_map )
    {
        SOAMAFR_map = new DCW_Library_Mgr("SAMAFR",
                                          gmsFlat,
                                          this);
    }

    QAction *llg_button = ui->actionTileRef_Lat_Long_Grid;

    bool state = llg_button->isChecked();

    SOAMAFR_map->set_map_feature(latLongGrid, state);

    std::cout << "process_LibRef_LatLong - end\n";
}

/* EOF */

