//-------------------------------------------------------------------------
// File : main.cpp
// Date : 29-May-26 : initial definition
//      : 07-Jun-26 : Add arg for earth model
//
// Description
//    Main entry point of Qt application that exercises some of the DCW
//    utilities.
//
//    This main was auto-generated by the "Qt Creator" tool ('qtcreator').
//    Adding arg processing should be OK since it's not expected to be
//    regenerated.  But if so, refer to 'git' log for history.
//
// Usage:
//
//       dcw_browse <flat | sphere | ellipse>
//
//    where the arguments specify the Earth projection model to be used.
//-------------------------------------------------------------------------
#include <iostream>

#include "dcw_browse_main_window.h"

#include <QApplication>

static void show_usage();

//--------------------------------------------------------
// FUNCTION: main
//
// DESCRIPTION:
//    Main entry function.  Instantiates the following
//    objects:
//       QApplication
//       dcw_browse_Main_Window
//-------------------------------------------------------- 
int main(int argc, char *argv[])
{
    if (argc != 2)
    {
        show_usage();
        std::exit(1);
    }

    QApplication a(argc, argv);

    const std::string earth_model = std::string(argv[1]);

    dcw_browse_Main_Window w(earth_model);

    w.show();

    int status = a.exec();

    return status;
}


//--------------------------------------------------------
// FUNCTION: main
//
// DESCRIPTION:
//    Invoked for invalid arg count.  The parse of the
//    argument is handled by the 'DCW_Browse' constructor.
//-------------------------------------------------------- 
static void show_usage()
{
    std::cout << "***> ERROR - invalid arg specified\n"
              << "***> USAGE:\n"
              << "***>    dcw_browse <flat | sphere | ellipse>\n"
              << "***> EXAMPLE:\n"
              << "***>     dcw_brose ellipse\n";
}

/* EOF */

