//-------------------------------------------------------------------------
// File : themes_info_dialog.h
// Date : 26-May-26 : initial definition
//
// Description:
//    Manage display of DCW "theme" data to the dialog pop-up.
//-------------------------------------------------------------------------
#ifndef THEMES_INFO_DIALOG_H
#define THEMES_INFO_DIALOG_H

#include <QDialog>

#include "ui_themes_info_dialog.h" // <-- Generated by qtcreator from ui

class Theme_Info_Dialog_Window : public QDialog
{
    Q_OBJECT

public:
    Theme_Info_Dialog_Window(QWidget *parent = nullptr);

    ~Theme_Info_Dialog_Window();

    void update(const std::string theme_data);

private:
    Ui_Theme_Info_Dialog_Window *ui;   // from ui_themes_info_dialog.h
};
#endif // THEMES_INFO_DIALOG_H

/* EOF */

