//-----------------------------------------------------------------------------
// File : gmsBitmapClass.cpp
// Date : 04-Nov-99 : initial definition
//        10-Nov-99 : code-review and clean-up
//
// Description:
//    This class defines a "device-independent bitmap" (DIB) object.  The
//    bitmap is created from the window whose handle is given in the
//    constructor.  The DIB can be saved to a file.  Such an object can be
//    used to implement "screen capture".
//
//    The DIB object (generated by this component) is fixed to a resolution
//    of 256 colors.  Such resolution (nowadays) is likely to be lower than
//    the resolution of most video hardware systems.  This was done because
//    many video boards no longer require a color lookup-table (i.e. a color
//    palette).  For example, this component was actually built/tested on a
//    PC system with a video card that implemented a 16-bit pixel.  The
//    RED and BLUE values were 5 bits and the GREEN value was 6 bits.  This
//    allowed for a range of 65535 colors without the need for a color table.
//    Furthermore, some systems now have 24 bit pixels (8-bits for each RGB).
//
//    But a DIB must include a color table ... at least if it is to be
//    read by the VC++ bitmap editor.  So, to keep things from getting out
//    of hand, the following "restrictions" (simplifications) were
//    implemented:
//
//           1) The color table has 256 entries (only).
//           2) Each pixel of the image is one byte (8 bits).
//           3) Each pixel value is an index into the color table.
//           4) No compression is used.
//           5) The simpler struct "BITMAPINFOHEADER" is used
//              (in lieu of "BITMAPV4HEADER" or "BITMAPV5HEADER").
//
// Acronyms:
//    DDB - Device Dependent Bitmap
//    DIB - Device Independent Bitmap
//    BM  - Bitmap
//    DC  - Device Context (i.e. Windows abstraction to video hardware)
//    GMS - Geographic Mapping System
//
// Copyright (c) 1999-2026, Timothy MacAndrew, all rights reserved
//-----------------------------------------------------------------------------

#include <gmsBitmapClass.h>
#include <stdio.h>


//---------------------------------
// Declare some constants
//---------------------------------

static const int Num_Colors = 256;

static const int Bits_Per_Byte = 8;


//---------------------------------
// Declare Static Member Functions
//---------------------------------

static void buildBitmapFileHeader
               (BITMAPINFOHEADER DIB_InfoHdr,
                BITMAPFILEHEADER *ptrTo_DIB_fileHdr);

static void buildBitmapInfoHeader
               (HDC              handleTo_DDB_DC,
                BITMAP           theDDB,
                BITMAPINFOHEADER *ptrToDIB_InfoHdr);

static RGBQUAD *buildColorTable
                  (HDC handleTo_DDB_DC);

static BYTE *constructImage
               (HDC      handleTo_DDB_DC,
                long int width,
                long int height,
                RGBQUAD  *ptrToColorTbl);

static BYTE *read_DIB_ImageFromFile
               (FILE             *fd,
                BITMAPFILEHEADER theBitmapFileHdr,
                BITMAPINFOHEADER theBitmapInfoHdr);

static RGBQUAD convertColorRefToRgbQuad
                  (COLORREF theColorRef);

static BYTE findColorInTableAndReturnIndex
                  (RGBQUAD theRGB,
                   RGBQUAD *ptrToColorTbl);


//---------------------------------
// Print utilities
//---------------------------------

static void printBitmapFileHeader
               (FILE             *fd,
                BITMAPFILEHEADER *ptrTo_DIB_fileHdr);

static void printBitmapInfoHeader
               (FILE             *fd,
                BITMAPINFOHEADER *ptrToDIB_InfoHdr);

static void printColorTable
               (FILE    *fd,
                int     numItems,
                RGBQUAD *ptrToColorTbl);


//---------------------------------
// Declare some debug utilities
//---------------------------------

static void debugShowSomeDeviceCapabilities
               (HDC hdc);


//-----------------------------------------------
// gmsBitmapClass
//
// Description:
//    Constructor.  Creates a device-independent
//    bitmap from the specified window handle.
//-----------------------------------------------
gmsBitmapClass::gmsBitmapClass (HWND windowHandle)

{
         HBITMAP    handleTo_DDB;
         HDC        handleTo_DDB_DC;
         BITMAP     theDDB;
         HDC        handleToWindow_DC;
         int        width, height;
         RECT       windowRectangle;

   GetWindowRect
      (windowHandle,
       &windowRectangle);

   width = windowRectangle.right - windowRectangle.left;

   height = windowRectangle.bottom - windowRectangle.top;

   //
   // Get a handle to the device context (DC) for the
   // entire window, including title bar, menus, and
   // scroll bars. 
   //
   handleToWindow_DC = GetWindowDC (windowHandle);

   handleTo_DDB = CreateCompatibleBitmap
                     (handleToWindow_DC,
                      width,
                      height);

   handleTo_DDB_DC = CreateCompatibleDC (handleToWindow_DC);

   ZeroMemory
      ((void *) &(gmsBitmapClass::theDIB),
       sizeof(gmsDeviceIndependentBitmapType));

   SelectObject (handleTo_DDB_DC, handleTo_DDB);

   BitBlt
      (handleTo_DDB_DC,
       0, 0,
       width, height,
       handleToWindow_DC,
       0, 0,
       SRCCOPY);

   GetObject
      (handleTo_DDB,
       sizeof (theDDB),
       &theDDB);

   //
   // Even though this is the second record in the
   // DIB, it has to be built first.
   //
   buildBitmapInfoHeader
      (handleTo_DDB_DC,
       theDDB,
       &(gmsBitmapClass::theDIB.bitmapInfoHdr));

   //
   // Now it's possible to build the file-header
   // of the DIB.
   //
   buildBitmapFileHeader
      (gmsBitmapClass::theDIB.bitmapInfoHdr,
       &(gmsBitmapClass::theDIB.bitmapFileHdr));

   // debugShowSomeDeviceCapabilities (handleTo_DDB_DC);

   //
   // Build the color table ...
   //
   gmsBitmapClass::theDIB.ptrToColorTbl = buildColorTable (handleTo_DDB_DC);

   if (gmsBitmapClass::theDIB.ptrToColorTbl == NULL)
      {
       DeleteObject (handleTo_DDB);

       DeleteDC (handleTo_DDB_DC);

       ReleaseDC (windowHandle, handleToWindow_DC);

       return;
      }

   //
   // ... and finally the image
   //
   gmsBitmapClass::theDIB.ptrToImage =
      constructImage
         (handleTo_DDB_DC,
          theDDB.bmWidth,
          theDDB.bmHeight,
          gmsBitmapClass::theDIB.ptrToColorTbl);

   DeleteObject (handleTo_DDB);

   DeleteDC (handleTo_DDB_DC);

   ReleaseDC (windowHandle, handleToWindow_DC);

   //
   // Memory leak?
   // ------------
   //    MSDN Library does not indicate that the
   //    bitmap's pointer to the bits (i.e
   //    theDDB.bmBits) should be 'freed'.
   //
}


//---------------------------------------------
// gmsBitmapClass
//
// Description:
//    Constructor.  Opens a device-independent
//    bitmap from the named file.
//---------------------------------------------
gmsBitmapClass::gmsBitmapClass (const char *nameOfFile)

{
         FILE *fd;
         int  numItemsRead;
         int  numItemsInColorTable;
         int  offsetToColorTbl;
         int  i;

   fd = fopen
           (nameOfFile,
            "rb");

   if (fd == NULL)
      {
       MessageBoxA
          (NULL,
           "Can not open specified bitmap file",
           "Open failed",
           MB_OK);

       return;
      }

   ZeroMemory
      ((void *) &(gmsBitmapClass::theDIB),
       sizeof(gmsDeviceIndependentBitmapType));

   //
   // Read the BITMAPFILEHEADER
   //
   numItemsRead = fread
                     ((void *) &(gmsBitmapClass::theDIB.bitmapFileHdr),
                      sizeof (BITMAPFILEHEADER),
                      1,
                      fd);

   if ( numItemsRead != 1 )
      {
       MessageBoxA
          (NULL,
           "Can't read file-header of DI bitmap",
           "Error Reading DIB",
           MB_OK);

       fclose (fd);

       return;
      }

   //
   // Read the BITMAPINFOHEADER.  The BITMAPV4HEADER struct
   // and the BITMAPV5HEADER struct are not considered here
   // for simplification.  The first 11 attributes of the V4
   // and V5 structs are the same as BITMAPINFOHEADER.  Thus,
   // if V4 or V5 data is actually in the file, those values
   // are ignored.
   //
   numItemsRead = fread
                    ((void *) &(gmsBitmapClass::theDIB.bitmapInfoHdr),
                     sizeof (BITMAPINFOHEADER),
                     1,
                     fd);

   if ( numItemsRead != 1 )
      {
       MessageBoxA
          (NULL,
           "Can't read INFO-header of DI bitmap",
           "Error reading DIB",
           MB_OK);

       fclose (fd);

       return;
      }

   //
   // Read the color table.  Have to figure out where the
   // color table starts because the BITMAPINFOHEADER could
   // have been the V4 or V5 header and only the first 11
   // attributes were read.
   //
   offsetToColorTbl = sizeof(BITMAPFILEHEADER) +
                      gmsBitmapClass::theDIB.bitmapInfoHdr.biSize;

   fseek (fd, offsetToColorTbl, SEEK_SET);

   numItemsInColorTable =
      (gmsBitmapClass::theDIB.bitmapFileHdr.bfOffBits -
       (sizeof(BITMAPFILEHEADER) +
        gmsBitmapClass::theDIB.bitmapInfoHdr.biSize)) / sizeof(RGBQUAD);

   gmsBitmapClass::theDIB.ptrToColorTbl = new RGBQUAD[numItemsInColorTable];

   for (i = 0; i < numItemsInColorTable; i++)
      {
       numItemsRead = fread
                       ((void *) &(gmsBitmapClass::theDIB.ptrToColorTbl[i]),
                        sizeof (RGBQUAD),
                        1,
                        fd);
      }

   //
   // Read the pixel values of the image ...
   //
   gmsBitmapClass::theDIB.ptrToImage =
      read_DIB_ImageFromFile
         (fd,
          gmsBitmapClass::theDIB.bitmapFileHdr,
          gmsBitmapClass::theDIB.bitmapInfoHdr);

   //
   // Done building object
   //
   fclose (fd);
}


//-----------------------------------------------
// ~gmsBitmapClass
//
// Description:
//    Destructor.  Deletes the device-independent
//    bitmap.
//-----------------------------------------------
gmsBitmapClass::~gmsBitmapClass ()

{
   if (gmsBitmapClass::theDIB.ptrToColorTbl != NULL)
      {
       delete gmsBitmapClass::theDIB.ptrToColorTbl;
      }

   if (gmsBitmapClass::theDIB.ptrToImage != NULL)
      {
       delete gmsBitmapClass::theDIB.ptrToImage;
      }
}


//-----------------------------------------------
// gmsSaveBitmap
//
// Description:
//    Method to save the device-independent
//    bitmap to the specified file.
//-----------------------------------------------
void gmsBitmapClass::gmsSaveBitmap (const char *nameOfFile)

{
         FILE          *fileDescriptor;
         char          errMessage[512];
         int           numItemsWritten;
         unsigned char *ptrToImage;
         int           numBytesInImage;
         int           i;

   fileDescriptor = fopen (nameOfFile,
                           "wb+");

   if (fileDescriptor == NULL)
      {
       sprintf(errMessage, "Cannot open : %s", nameOfFile);

       MessageBoxA
          (NULL,
           errMessage,
           "Open failed",
           MB_OK);

       return;
      }

   //
   // Write the BITMAPFILEHEADER
   //
   numItemsWritten = fwrite
                        ((void *) &(gmsBitmapClass::theDIB.bitmapFileHdr),
                         sizeof (BITMAPFILEHEADER),
                         1,
                         fileDescriptor);

   if ( numItemsWritten != 1 )
      {
       MessageBoxA
          (NULL,
           "Can't write file-header of DI bitmap",
           "Error Writing DIB",
           MB_OK);

       fclose (fileDescriptor);

       return;
      }

   //
   // Write the BITMAPINFOHEADER
   //
   numItemsWritten = fwrite
                        ((void *) &(gmsBitmapClass::theDIB.bitmapInfoHdr),
                         sizeof (BITMAPINFOHEADER),
                         1,
                         fileDescriptor);

   if ( numItemsWritten != 1 )
      {
       MessageBoxA
          (NULL,
           "Can't write INFO-header of DI bitmap",
           "Error Writing DIB",
           MB_OK);

       fclose (fileDescriptor);

       return;
      }

   //
   // Write the Color Table
   //
   if (gmsBitmapClass::theDIB.ptrToColorTbl != NULL)
      {
       for (i = 0; i < Num_Colors; i++)
          {
           numItemsWritten =
              fwrite
                 ((void *) &(gmsBitmapClass::theDIB.ptrToColorTbl[i]),
                  sizeof(RGBQUAD),
                  1,
                  fileDescriptor);

           if ( numItemsWritten != 1 )
              {
               MessageBoxA
                  (NULL,
                   "Error : failed writing RGB record",
                   "Error Writing DI",
                   MB_OK);

               fclose (fileDescriptor);

               return;
              }
          }
      }

   //
   // Write the Bitmap/Image
   //
   if (gmsBitmapClass::theDIB.ptrToImage != NULL)
      {
       ptrToImage = (unsigned char *) gmsBitmapClass::theDIB.ptrToImage;

       numBytesInImage =
          gmsBitmapClass::theDIB.bitmapFileHdr.bfSize -
          gmsBitmapClass::theDIB.bitmapFileHdr.bfOffBits;

       for (i = 0; i < numBytesInImage; i++)
          {
           numItemsWritten = fwrite
                                ((void *) &ptrToImage[i],
                                 sizeof(unsigned char),
                                 1,
                                 fileDescriptor);

           if ( numItemsWritten != 1 )
              {
               MessageBoxA
                  (NULL,
                   "Error : failed writing bytes of image",
                   "Error Writing DI",
                   MB_OK);

               fclose (fileDescriptor);

               return;
              }
          }
      }

   fclose (fileDescriptor);
}


//-----------------------------------------------
// gmsPrintContentsOfBitmap
//
// Description:
//    Method that writes the contents of the
//    bitmap object to file.
//-----------------------------------------------
void gmsBitmapClass::gmsPrintContentsOfBitmap
                        (const char *nameOfFile)

{
         int  numItemsInColorTable;
         FILE *fd;
         char errMessage[256];

   fd = fopen
           (nameOfFile,
            "w+");

   if (fd == NULL)
      {
       sprintf(errMessage, "Cannot open : %s", nameOfFile);

       MessageBoxA
          (NULL,
           errMessage,
           "Can not save bitmap",
           MB_OK);

       return;
      }

   fprintf(fd, "__________________________\n");
   fprintf(fd, "Device-Independent-Bitmap:\n");

   printBitmapFileHeader
               (fd,
                &(gmsBitmapClass::theDIB.bitmapFileHdr));

   printBitmapInfoHeader
               (fd,
                &(gmsBitmapClass::theDIB.bitmapInfoHdr));

   numItemsInColorTable =
      (gmsBitmapClass::theDIB.bitmapFileHdr.bfOffBits -
       (sizeof(BITMAPFILEHEADER) +
        gmsBitmapClass::theDIB.bitmapInfoHdr.biSize)) / sizeof(RGBQUAD);

   printColorTable
      (fd, 
       numItemsInColorTable,
       gmsBitmapClass::theDIB.ptrToColorTbl);

   fclose (fd);
}


        //---------------------------
        //  Static Member Functions
        //---------------------------


//-------------------------------------------------
// buildBitmapFileHeader
//
// Desciption:
//    This function builds a "Bitmap File Header"
//    object.  It uses information from the given
//    "Bitmap Information Header" object.  The
//    file header struct is the first component
//    in a file of a DIB.  This information is
//    used by bitmap-readers to read the cor-
//    responding image.
//-------------------------------------------------
static void buildBitmapFileHeader
               (BITMAPINFOHEADER DIB_InfoHdr,
                BITMAPFILEHEADER *ptrTo_DIB_fileHdr)

{
         int       offsetToImage;
         int       numBytesInColorTable;
         int       totalSizeOfDib;
         const int dontCare = 0;

   numBytesInColorTable = (sizeof(RGBQUAD)) * Num_Colors;

   offsetToImage = (sizeof(BITMAPFILEHEADER)) +
                   DIB_InfoHdr.biSize +
                   numBytesInColorTable;

   totalSizeOfDib = offsetToImage + DIB_InfoHdr.biSizeImage;

   ptrTo_DIB_fileHdr->bfSize      = totalSizeOfDib;
   ptrTo_DIB_fileHdr->bfType      = 0x4D42; // i.e. the string "BM"
   ptrTo_DIB_fileHdr->bfOffBits   = offsetToImage;
   ptrTo_DIB_fileHdr->bfReserved1 = dontCare;
   ptrTo_DIB_fileHdr->bfReserved2 = dontCare;
}


//-------------------------------------------------
// buildBitmapInfoHeader
//
// Desciption:
//    This utility constructs a BITMAPINFOHEADER
//    record.  It uses information from the DDB
//    and its device-context (DC) to build the
//    record.
//-------------------------------------------------
static void buildBitmapInfoHeader
               (HDC              handleTo_DDB_DC,
                BITMAP           theDDB,
                BITMAPINFOHEADER *ptrToDIB_InfoHdr)

{
         int         xPelsPerMeter;
         int         yPelsPerMeter;
         float       widthOfScreen_millimeters;
         float       heightOfScreen_millimeters;
         float       widthOfScreen_meters;
         float       heightOfScreen_meters;
         float       widthOfScreen_pixels;
         float       heightOfScreen_pixels;
         const float m_per_mm = (1.0f / 1000.0f);
         int         padding;
         int         sizeOfImageBytes;

   //
   // Gather statistics ...
   //
   widthOfScreen_millimeters = (float) GetDeviceCaps
                                          (handleTo_DDB_DC,
                                           HORZSIZE);

   heightOfScreen_millimeters = (float) GetDeviceCaps
                                           (handleTo_DDB_DC,
                                            VERTSIZE);

   widthOfScreen_pixels = (float) GetDeviceCaps
                                     (handleTo_DDB_DC,
                                      HORZRES);

   heightOfScreen_pixels = (float) GetDeviceCaps
                                      (handleTo_DDB_DC,
                                       VERTRES);

   widthOfScreen_meters = widthOfScreen_millimeters * m_per_mm;

   xPelsPerMeter = (int) (widthOfScreen_pixels / widthOfScreen_meters);

   heightOfScreen_meters = heightOfScreen_millimeters * m_per_mm;

   yPelsPerMeter = (int) (heightOfScreen_pixels / heightOfScreen_meters);

   padding = theDDB.bmWidth % 4; // image must be 32-bit addressable

   sizeOfImageBytes = (theDDB.bmWidth + padding) * theDDB.bmHeight;

   //
   // Now build the record
   //
   ptrToDIB_InfoHdr->biSize          = sizeof (BITMAPINFOHEADER);
   ptrToDIB_InfoHdr->biWidth         = theDDB.bmWidth;
   ptrToDIB_InfoHdr->biHeight        = theDDB.bmHeight;
   ptrToDIB_InfoHdr->biPlanes        = 1;
   ptrToDIB_InfoHdr->biBitCount      = Bits_Per_Byte; // or theDDB.bmBitsPixel
   ptrToDIB_InfoHdr->biCompression   = BI_RGB;        // i.e. no compression
   ptrToDIB_InfoHdr->biSizeImage     = sizeOfImageBytes;
   ptrToDIB_InfoHdr->biXPelsPerMeter = xPelsPerMeter;
   ptrToDIB_InfoHdr->biYPelsPerMeter = yPelsPerMeter;
   ptrToDIB_InfoHdr->biClrUsed       = Num_Colors;
   ptrToDIB_InfoHdr->biClrImportant  = 0;
}




//-------------------------------------------------
// buildColorTable
//
// Desciption:
//    This utility constructs a color table for the
//    DIB.  This utility uses the "system palette"
//    (which is why the DC to the DDB is needed)
//    to construct the color table.
//-------------------------------------------------
static RGBQUAD *buildColorTable
                  (HDC handleTo_DDB_DC)

{
         RGBQUAD       *ptrToColorTbl;
         UINT          status;
         const UINT    startIndex = 0;
         PALETTEENTRY  *ptrToPalette;
         int           i;
         int           rasterCapabilities;
         int           paletteIsSupported;

   rasterCapabilities = GetDeviceCaps
                           (handleTo_DDB_DC,
                            RASTERCAPS);

   paletteIsSupported =  rasterCapabilities & (int) RC_DI_BITMAP;

   if ( ! paletteIsSupported )
      {
       MessageBoxA
          (NULL,
           "ERROR : This system has NO support for Dev Indep Bitmaps.",
           "No color table constructed",
           MB_OK);

       return NULL;
      }

   ptrToPalette = new PALETTEENTRY[Num_Colors];

   status = GetSystemPaletteEntries
               (handleTo_DDB_DC,
                startIndex,
                Num_Colors,
                ptrToPalette);

   if (status != Num_Colors)
      {
       MessageBoxA
          (NULL,
           "Unable to get Palette Table",
           "Build Color Table : FAIL",
           MB_OK);

       delete ptrToPalette;

       return NULL;
      }

   ptrToColorTbl = new RGBQUAD[Num_Colors];

   ZeroMemory
      ( (void *) ptrToColorTbl,
        (sizeof(RGBQUAD) * Num_Colors) );

   for (i = 0; i < Num_Colors; i++)
      {
       ptrToColorTbl[i].rgbRed      = ptrToPalette[i].peRed;
       ptrToColorTbl[i].rgbGreen    = ptrToPalette[i].peGreen;
       ptrToColorTbl[i].rgbBlue     = ptrToPalette[i].peBlue;
       ptrToColorTbl[i].rgbReserved = 0;
      }

   delete ptrToPalette;

   return ptrToColorTbl;
}


//-------------------------------------------------
// constructImage
//
// Desciption:
//    This utility builds an array of BYTEs that
//    represents the pixels of the image.  This
//    utility uses the "GetPixel" utility on the
//    DDB and then converts the 32-bit COLORREF
//    value to an RGBQUAD record.  The color table
//    is then searched for that RGBQUAD value and
//    the index used to set the pixel value in the
//    image array.  That image array is then
//    returned to the caller.
//-------------------------------------------------
static BYTE *constructImage
               (HDC      handleTo_DDB_DC,
                long int width,
                long int height,
                RGBQUAD  *ptrToColorTbl)

{
         int      padding;
         int      sizeOfImage;
         BYTE     *ptrToBits;
         COLORREF tempColorRef;
         RGBQUAD  theRGB;
         int      row, col, index;

   padding = width % 4;

   sizeOfImage = (width + padding) * height;

   ptrToBits = new BYTE[sizeOfImage];

   ZeroMemory
      ( (void *) ptrToBits,
       sizeOfImage);

   for (col = 0; col < width; col++)
      for (row = 0; row < height; row++)
         {
          tempColorRef = GetPixel
                            (handleTo_DDB_DC,
                             col,
                             (height - row)); // makes image right-side up

          theRGB = convertColorRefToRgbQuad (tempColorRef);

          index = row * (width - 1) + col + row + (row * padding);

          if (index >= sizeOfImage)
             {
                    char errMsg[128];

              sprintf(errMsg, "Error constructing image at pixel %d",
                      index);

              MessageBoxA
                 (NULL,
                  errMsg,
                  "Index to Bits Tbl too big",
                  MB_OK);

              delete ptrToBits;

              return NULL;
             }

          ptrToBits[index] = findColorInTableAndReturnIndex
                                    (theRGB,
                                     ptrToColorTbl);
         }

   return ptrToBits;
}


//-------------------------------------------------
// read_DIB_ImageFromFile
//
// Desciption:
//    This utility reads the image portion of a
//    DIB from the specified file.
//
//    Warning:
//       This utility only works for images made
//       of BYTE-sized pixels.  Other bits-per-
//       pixel architectures (e.g. 4, 16, 24) will
//       likely fail.
//-------------------------------------------------
static BYTE *read_DIB_ImageFromFile
               (FILE             *fd,
                BITMAPFILEHEADER theBitmapFileHdr,
                BITMAPINFOHEADER theBitmapInfoHdr)

{
         const int numBytesInImage = theBitmapInfoHdr.biSizeImage;
         BYTE      *ptrToImage;
         int       i;
         int       numItemsRead;

   ptrToImage = new BYTE[numBytesInImage];

   fseek
      (fd,
       theBitmapFileHdr.bfOffBits,
       SEEK_SET);

   for (i = 0; i < numBytesInImage; i++)
      {
       numItemsRead = fread
                       ((void *) &(ptrToImage[i]),
                        sizeof (BYTE),
                        1,
                        fd);
      }

   return ptrToImage;
}


//-------------------------------------------------
// printBitmapFileHeader
//
// Desciption:
//    Utility that prints the contents of the
//    BITMAPFILEHEADER to the specified file.
//-------------------------------------------------
static void printBitmapFileHeader
               (FILE             *fd,
                BITMAPFILEHEADER *ptrTo_DIB_fileHdr)

{
   fprintf (fd, "   ________________\n");
   fprintf (fd, "   BITMAPFILEHEADER\n");

   fprintf(fd, "      ---> Size of this record = %d bytes\n",
           sizeof(BITMAPFILEHEADER));

   fprintf(fd, "      bfOffBits   = %d bytes (i.e. offset to image)\n",
           ptrTo_DIB_fileHdr->bfOffBits);

   fprintf(fd, "      bfType      = %x\n",
           ptrTo_DIB_fileHdr->bfType);

   fprintf(fd, "      bfSize      = %d bytes (total size of BMP file)\n",
           ptrTo_DIB_fileHdr->bfSize);

   fprintf(fd, "      bfReserved1 = %d (don't care)\n",
           ptrTo_DIB_fileHdr->bfReserved1);

   fprintf(fd, "      bfReserved2 = %d (don't care)\n",
           ptrTo_DIB_fileHdr->bfReserved2);
}


//-------------------------------------------------
// printBitmapInfoHeader
//
// Desciption:
//    Utility that prints the contents of the
//    BITMAPINFOHEADER to the specified file.
//-------------------------------------------------
static void printBitmapInfoHeader
               (FILE             *fd,
                BITMAPINFOHEADER *ptrToDIB_InfoHdr)

{
         static char *compressionTbl[5] =
            { { "BI_RGB       : uncompressed format" },
              { "BI_RLE8      : run-length encoded (8 bits per pixel)"},
              { "BI_RLE4      : RLE (4 bits per pixel)" },
              { "BI_BITFIELDS : uncompressed, three DWORD color masks" },
              { "BI_JPEG" } }; 

   //
   // the BITMAPINFOHEADER
   //
   fprintf (fd, "   ________________\n");
   fprintf (fd, "   BITMAPINFOHEADER\n");

   fprintf(fd, "   Size            = %d bytes (of this bitmap-info-hdr)\n",
           ptrToDIB_InfoHdr->biSize);

   fprintf(fd, "   Width           = %d pixels (of image)\n",
           ptrToDIB_InfoHdr->biWidth);

   fprintf(fd, "   Height          = %d pixels (of image)\n",
           ptrToDIB_InfoHdr->biHeight);

   fprintf(fd, "   Planes          = %d\n",
           ptrToDIB_InfoHdr->biPlanes);

   fprintf(fd, "   BitCount        = %d (i.e. bits-per-pixel)\n",
           ptrToDIB_InfoHdr->biBitCount);

   if (ptrToDIB_InfoHdr->biCompression == BI_RGB)
      {
       fprintf(fd, "   Compression     = %s\n",
               compressionTbl[0]);
      }

   else if (ptrToDIB_InfoHdr->biCompression == BI_RLE8)
      {
       fprintf(fd, "   Compression     = %s\n",
               compressionTbl[1]);
      }

   else if (ptrToDIB_InfoHdr->biCompression == BI_RLE4)
      {
       fprintf(fd, "   Compression     = %s\n",
               compressionTbl[2]);
      }

   else if (ptrToDIB_InfoHdr->biCompression == BI_BITFIELDS)
      {
       fprintf(fd, "   Compression     = %s\n",
               compressionTbl[3]);
      }

   else
      {
       fprintf(fd, "   Compression     = UNKNOWN\n");
      }

   fprintf(fd, "   Size of Image   = %d (bytes)\n",
           ptrToDIB_InfoHdr->biSizeImage);

   fprintf(fd, "   X Pels/Meter    = %d\n",
           ptrToDIB_InfoHdr->biXPelsPerMeter);

   fprintf(fd, "   Y Pels/Meter    = %d\n",
           ptrToDIB_InfoHdr->biYPelsPerMeter);

   fprintf(fd, "   Color Used      = %d (num entries in color tbl)\n",
           ptrToDIB_InfoHdr->biClrUsed);

   fprintf(fd, "   Color Important = %d\n",
           ptrToDIB_InfoHdr->biClrImportant);
}


//-------------------------------------------------
// printColorTable
//
// Desciption:
//    Utility that prints the contents of the
//    color-table of the DIB to the specified file.
//-------------------------------------------------
static void printColorTable
               (FILE    *fd,
                int     numItems,
                RGBQUAD *ptrToColorTbl)

{
         int i;

   fprintf (fd, "   ________________\n");
   fprintf (fd, "   Colormap Table:\n");

   if (ptrToColorTbl == NULL)
      {
       fprintf(fd, "      ---> color table is NULL <---\n");

       return;
      }

   fprintf(fd, "   ---> Size of RGBQUAD = %d bytes\n",
           sizeof(RGBQUAD));

   for (i = 0; i < numItems; i++)
      {
       fprintf(fd, "   %d) RED   = %d\n",
               i, ptrToColorTbl[i].rgbRed);

       fprintf(fd, "         GREEN = %d\n",
               ptrToColorTbl[i].rgbGreen);

       fprintf(fd, "         BLUE  = %d\n",
               ptrToColorTbl[i].rgbGreen);

       fprintf(fd, "         RSRVD = %d\n",
               ptrToColorTbl[i].rgbReserved);
      }
}


//-------------------------------------------------
// convertColorRefToRgbQuad
//
// Desciption:
//    This utility converts the specified COLORREF
//    value to an RGBQUAD record.
//
//    Notes:
//    ------
//       The COLORREF value is a 32-bit value used to
//       specify an RGB color. 
//
//       When specifying an explicit RGB color, the
//       COLORREF value has the following hexadecimal
//       form: 
//
//                   0x00bbggrr
//
//       The low-order byte contains a value for the
//       relative intensity of red; the second byte
//       contains a value for green; and the third
//       byte contains a value for blue. The high-order
//       byte must be zero. The maximum value for a
//       single byte is 0xFF.
//
//       Reference: MSDN Library Visual Studio 6.0
//                  April 1999.
//-------------------------------------------------
static RGBQUAD convertColorRefToRgbQuad
                  (COLORREF theColorRef)

{
         const COLORREF blueMask  = 0x00FF0000;
         const COLORREF greenMask = 0x0000FF00;
         const COLORREF redMask   = 0x000000FF;
         RGBQUAD        theAnswer;

   theAnswer.rgbRed      = (BYTE) (redMask & theColorRef);

   theAnswer.rgbGreen    = (BYTE) ((greenMask & theColorRef) >> 8);

   theAnswer.rgbBlue     = (BYTE) ((blueMask & theColorRef) >> 16);

   theAnswer.rgbReserved = (BYTE) 0;

   return theAnswer;
}


//-------------------------------------------------
// findColorInTableAndReturnIndex
//
// Desciption:
//    This utility searches the given color table
//    for the specified color "theRGB".  If the
//    color is found, the index into the color
//    table is returned and it becomes the pixel
//    value in the image of the DIB.  If the color
//    is NOT found in the color table, the first
//    index value is returned (which is likely to
//    be the color black).
//-------------------------------------------------
static BYTE findColorInTableAndReturnIndex
                  (RGBQUAD theRGB,
                   RGBQUAD *ptrToColorTbl)

{
         const BYTE Not_Found = 0; // safety valve
         int        i;

   for (i = 0; i < Num_Colors; i++)
      {
       if ( (theRGB.rgbRed   == ptrToColorTbl[i].rgbRed) &&
            (theRGB.rgbGreen == ptrToColorTbl[i].rgbGreen) &&
            (theRGB.rgbBlue  == ptrToColorTbl[i].rgbBlue) )

           return (BYTE) i;

      }

   return Not_Found;
}


//-------------------------------------------------
// debugShowSomeDeviceCapabilities
//
// Desciption:
//    This is a debug utility that is used to show
//    some of the video/graphics capabilities of
//    the current video hardware.  This information
//    might explain why something is not working.
//-------------------------------------------------
static void debugShowSomeDeviceCapabilities
               (HDC hdc)

{
         int        status;
         char       message[256];
         const char *title = { "Device Capabilities" };
         const int  numQueries = 4;
         const int  indexes[numQueries] = { NUMCOLORS,
                                            SIZEPALETTE,
                                            BITSPIXEL,
                                            RASTERCAPS };
         const char *features[numQueries] = { {"NUMCOLORS"},
                                              {"SIZEPALETTE"},
                                              {"BITSPIXEL"},
                                              {"RASTERCAPS"} };
         int        i;

   for (i = 0; i < numQueries; i++)
      {
       status = GetDeviceCaps
                   (hdc,
                    indexes[i]);

       sprintf(message, "%s = %x (hex)",
               features[i],
               status);

       MessageBoxA
          (NULL,
           message,
           title,
           MB_OK);
      }
}
